In [1]:
import pandas as pd
import requests
import yfinance as yf

print("Everything works!")

Everything works!

In [2]:
import yfinance as yf
import pandas as pd

# Download Brent Oil prices
brent = yf.download(
    "BZ=F",
    start="2022-01-01",
    end="2026-01-01",
    auto_adjust=True
)

# Keep only Close price
brent = brent[['Close']]

# Rename column
brent.columns = ['Brent_Price']

# Convert index to column
brent = brent.reset_index()

# Preview
print(brent.head())
print()
print(brent.tail())
print()
print(brent.shape)

[*********************100%***********************]  1 of 1 completed

        Date  Brent_Price
0 2022-01-03    78.980003
1 2022-01-04    80.000000
2 2022-01-05    80.800003
3 2022-01-06    81.989998
4 2022-01-07    81.750000

           Date  Brent_Price
1001 2025-12-24    62.240002
1002 2025-12-26    60.639999
1003 2025-12-29    61.939999
1004 2025-12-30    61.919998
1005 2025-12-31    60.849998

(1006, 2)

In [3]:
brent.to_csv('brent_prices.csv', index=False)

In [4]:
from google.colab import files

files.download('brent_prices.csv')

In [5]:
#TTF Natural Gas
import yfinance as yf
import pandas as pd

# TTF Natural Gas Futures
ttf = yf.download(
    "TTF=F",
    start="2022-01-01",
    end="2026-01-01",
    auto_adjust=True
)

ttf = ttf[['Close']]
ttf.columns = ['TTF_Price']
ttf = ttf.reset_index()

print(ttf.head())
print()
print(ttf.tail())
print()
print(ttf.shape)

[*********************100%***********************]  1 of 1 completed

        Date  TTF_Price
0 2022-01-03  80.433998
1 2022-01-04  88.740997
2 2022-01-05  91.522003
3 2022-01-06  96.501999
4 2022-01-07  88.174004

           Date  TTF_Price
1000 2025-12-24  28.094999
1001 2025-12-26  28.094999
1002 2025-12-29  28.534000
1003 2025-12-30  27.766001
1004 2025-12-31  28.160999

(1005, 2)

In [6]:
ttf.to_csv('ttf_prices.csv', index=False)
from google.colab import files
files.download('ttf_prices.csv')

In [7]:
#EUA Carbon Prices
import yfinance as yf
import pandas as pd

# EUA Carbon Futures
eua = yf.download(
    "CO2.L",
    start="2022-01-01",
    end="2026-01-01",
    auto_adjust=True
)

print(eua.head())
print()
print(eua.shape)

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open Volume
Ticker          CO2.L      CO2.L      CO2.L      CO2.L  CO2.L
Date
2022-01-04  84.800003  86.000000  83.559998  83.559998   1035
2022-01-05  87.519997  88.000000  85.500000  86.239998   2077
2022-01-06  86.815002  87.500000  86.129997  87.500000    667
2022-01-07  85.300003  87.120003  85.449997  87.120003   3400
2022-01-10  80.419998  87.440002  80.000000  87.440002   3521

(1008, 5)

In [8]:
#data cleaning EUA
# keep only Close
eua = eua[['Close']]

# rename column
eua.columns = ['EUA_Price']

# transform Date to normal column
eua = eua.reset_index()

print(eua.head())
print()
print(eua.shape)

        Date  EUA_Price
0 2022-01-04  84.800003
1 2022-01-05  87.519997
2 2022-01-06  86.815002
3 2022-01-07  85.300003
4 2022-01-10  80.419998

(1008, 2)

In [9]:
eua.to_csv('eua_prices.csv', index=False)
from google.colab import files
files.download('eua_prices.csv')

In [10]:
import yfinance as yf
import pandas as pd

# European energy proxy index
power = yf.download(
    "ENR.DE",   # European energy sector proxy (Germany utilities)
    start="2022-01-01",
    end="2026-01-01",
    auto_adjust=True
)

power = power[['Close']].reset_index()
power.columns = ['Date', 'Power_Index']

power.head()

[*********************100%***********************]  1 of 1 completed

        Date  Power_Index
0 2022-01-03    23.101803
1 2022-01-04    23.230589
2 2022-01-05    23.329651
3 2022-01-06    22.606482
4 2022-01-07    22.378633

In [11]:
power['Country'] = 'EU'
power.head()

        Date  Power_Index Country
0 2022-01-03    23.101803      EU
1 2022-01-04    23.230589      EU
2 2022-01-05    23.329651      EU
3 2022-01-06    22.606482      EU
4 2022-01-07    22.378633      EU

In [12]:
#Merge in ONE market table
# ensure Date is datetime
brent['Date'] = pd.to_datetime(brent['Date'])
ttf['Date'] = pd.to_datetime(ttf['Date'])
eua['Date'] = pd.to_datetime(eua['Date'])
power['Date'] = pd.to_datetime(power['Date'])

# merge step by step
df = brent.merge(ttf, on='Date', how='inner')
df = df.merge(eua, on='Date', how='inner')
df = df.merge(power[['Date','Power_Index']], on='Date', how='inner')

df.head()

        Date  Brent_Price  TTF_Price  EUA_Price  Power_Index
0 2022-01-04    80.000000  88.740997  84.800003    23.230589
1 2022-01-05    80.800003  91.522003  87.519997    23.329651
2 2022-01-06    81.989998  96.501999  86.815002    22.606482
3 2022-01-07    81.750000  88.174004  85.300003    22.378633
4 2022-01-10    80.870003  84.607002  80.419998    21.843687

In [13]:
df.to_csv("energy_master_dataset.csv", index=False)

In [14]:
df_clean = df[[
    'Date',
    'Brent_Price',
    'TTF_Price',
    'EUA_Price',
    'Power_Index'
]]

In [15]:
df_clean.to_csv("energy_prices_clean.csv", index=False)

In [16]:
df.to_csv('energy_prices_clean.csv', index=False)

In [17]:
from google.colab import files
files.download('energy_prices_clean.csv')